# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luck and Skill
author: Simon Brown
email: simon@luckandskill.io
description: > # this means to ignore newlines until "baseurl:"
  Success comes from some combination of luck and skill; we are right to be 
  proud of our skill, but we should also remember to be humble about our luck. 
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.luckandskill.io" # the base hostname & protocol for your site
twitter_username: caelyxsec
github_username:  caelyx
paginate: 5

# Build settings
markdown: kramdown

timezone: Australia/Sydney
